

INSERT INTO `products`(`english_name`, `polish_name`, `glycemic_index`, `carbohydrate`) VALUES ('honey', 'miód', '52.27', '82'), ('milk', 'mleko', '38.0', '5');
INSERT INTO `products`(`english_name`, `polish_name`, `glycemic_index`, `carbohydrate`) VALUES ('soy milk', 'napój sojowy', '33.42', '3'), ('yogurt', 'jogurt', '19.0', '5');
INSERT INTO `products`(`english_name`, `polish_name`, `glycemic_index`, `carbohydrate`) VALUES ('white bread', 'chleb pszenny', '74.78', '46');
INSERT INTO `products`(`english_name`, `polish_name`, `glycemic_index`, `carbohydrate`) VALUES ('wholemeal bread', 'chleb pełnoziarnisty', '69.7', '34');
INSERT INTO `products`(`english_name`, `polish_name`, `glycemic_index`, `carbohydrate`) VALUES ('rye bread', 'chleb żytni', '52.33', '42');
INSERT INTO `products`(`english_name`, `polish_name`, `glycemic_index`, `carbohydrate`) VALUES ('gluten free bread', 'chleb bezglutenowy', '66.0', '51');
INSERT INTO `products`(`english_name`, `polish_name`, `glycemic_index`, `carbohydrate`) VALUES ('quick oats', 'płatki owsiane błyskawiczne', '65.0', '59');
INSERT INTO `products`(`english_name`, `polish_name`, `glycemic_index`, `carbohydrate`) VALUES ('steel oats', 'płatki owsiane górskie', '57.0', '55');
INSERT INTO `products`(`english_name`, `polish_name`, `glycemic_index`, `carbohydrate`) VALUES ('white rice', 'ryż biały', '61.19', '79');
INSERT INTO `products`(`english_name`, `polish_name`, `glycemic_index`, `carbohydrate`) VALUES ('brown rice', 'ryż brązowy', '58.75', '73');
INSERT INTO `products`(`english_name`, `polish_name`, `glycemic_index`, `carbohydrate`) VALUES ('whild rice', 'ryż dziki', '61.19', '79');
INSERT INTO `products`(`english_name`, `polish_name`, `glycemic_index`, `carbohydrate`) VALUES ('cous cous', 'kuskus', '65.0', '72');
INSERT INTO `products`(`english_name`, `polish_name`, `glycemic_index`, `carbohydrate`) VALUES ('cooked pasta', 'makaron', '48.5', '29');
INSERT INTO `products`(`english_name`, `polish_name`, `glycemic_index`, `carbohydrate`) VALUES ('cooked wholemeal pasta', 'makaron pełnoziarnisty', '58.0', '22');
INSERT INTO `products`(`english_name`, `polish_name`, `glycemic_index`, `carbohydrate`) VALUES ('rice pasta', 'makaron ryżowy', '63.5', '71');
INSERT INTO `products`(`english_name`, `polish_name`, `glycemic_index`, `carbohydrate`) VALUES ('apple', 'jabłko', '32.0', '11');
INSERT INTO `products`(`english_name`, `polish_name`, `glycemic_index`, `carbohydrate`) VALUES ( 'banana', 'banan', '54.78', '20');
INSERT INTO `products`(`english_name`, `polish_name`, `glycemic_index`, `carbohydrate`) VALUES ('cherries', 'wiśnie', '22.0', '14');
INSERT INTO `products`(`english_name`, `polish_name`, `glycemic_index`, `carbohydrate`) VALUES ('grapefruit', 'grapefruit', '25.0', '9');
INSERT INTO `products`(`english_name`, `polish_name`, `glycemic_index`, `carbohydrate`) VALUES ('grapes', 'winogrona', '46.0', '17');
INSERT INTO `products`(`english_name`, `polish_name`, `glycemic_index`, `carbohydrate`) VALUES ('kiwi', 'kiwi', '52.67', '12');
INSERT INTO `products`(`english_name`, `polish_name`, `glycemic_index`, `carbohydrate`) VALUES ('mango', 'mango', '51.75', '13');
INSERT INTO `products`(`english_name`, `polish_name`, `glycemic_index`, `carbohydrate`) VALUES ('orange', 'pomarancza', '42.5', '9');
INSERT INTO `products`(`english_name`, `polish_name`, `glycemic_index`, `carbohydrate`) VALUES ('papaya', 'papaja', '58.75', '9');
INSERT INTO `products`(`english_name`, `polish_name`, `glycemic_index`, `carbohydrate`) VALUES ('peach', 'brzoskwinia', '40.25', '8');
INSERT INTO `products`(`english_name`, `polish_name`, `glycemic_index`, `carbohydrate`) VALUES ('pear', 'gruszka', '36.75', '12');
INSERT INTO `products`(`english_name`, `polish_name`, `glycemic_index`, `carbohydrate`) VALUES ('pineapple', 'ananas', '58.67', '12');
INSERT INTO `products`(`english_name`, `polish_name`, `glycemic_index`, `carbohydrate`) VALUES ('plum', 'śliwka', '38.67', '10');
INSERT INTO `products`(`english_name`, `polish_name`, `glycemic_index`, `carbohydrate`) VALUES ('raisins', 'rodzynki', '58.8', '72');
INSERT INTO `products`(`english_name`, `polish_name`, `glycemic_index`, `carbohydrate`) VALUES ('strawberry', 'truskawki', '40.0', '6');
INSERT INTO `products`(`english_name`, `polish_name`, `glycemic_index`, `carbohydrate`) VALUES ('watermelon', 'arbuz', '74.67', '7');
INSERT INTO `products`(`english_name`, `polish_name`, `glycemic_index`, `carbohydrate`) VALUES ('carrot juice', 'sok marchwiowy', '43.0', '8');
INSERT INTO `products`(`english_name`, `polish_name`, `glycemic_index`, `carbohydrate`) VALUES ('grapefruit juice', 'sok grapefruitowy', '48.0', '11');
INSERT INTO `products`(`english_name`, `polish_name`, `glycemic_index`, `carbohydrate`) VALUES ('orange juice', 'sok pomarnczowy', '52.0', '10');
INSERT INTO `products`(`english_name`, `polish_name`, `glycemic_index`, `carbohydrate`) VALUES ('tomato juice', 'sok pomidorowy', '31.33', '4');
INSERT INTO `products`(`english_name`, `polish_name`, `glycemic_index`, `carbohydrate`) VALUES ('apple juice', 'sok jabłkowy', '40.75', '11');
INSERT INTO `products`(`english_name`, `polish_name`, `glycemic_index`, `carbohydrate`) VALUES ('corn', 'kukurydza', '55.5', '19');
INSERT INTO `products`(`english_name`, `polish_name`, `glycemic_index`, `carbohydrate`) VALUES ('potato', 'ziemniaki', '83.75', '15');
INSERT INTO `products`(`english_name`, `polish_name`, `glycemic_index`, `carbohydrate`) VALUES ('sweet potato', 'bataty', '58.0', '17');
INSERT INTO `products`(`english_name`, `polish_name`, `glycemic_index`, `carbohydrate`) VALUES ('peas', 'groszek zielony', '44.33', '9');
INSERT INTO `products`(`english_name`, `polish_name`, `glycemic_index`, `carbohydrate`) VALUES ('red beans', 'fasola czerwona', '31.29', '15');
INSERT INTO `products`(`english_name`, `polish_name`, `glycemic_index`, `carbohydrate`) VALUES ('soybeans', 'soja', '15.8', '4');
INSERT INTO `products`(`english_name`, `polish_name`, `glycemic_index`, `carbohydrate`) VALUES ('mung beans', 'fasola mung', '0.0', '0');
INSERT INTO `products`(`english_name`, `polish_name`, `glycemic_index`, `carbohydrate`) VALUES ('chickpeas', 'ciecierzyca', '25.75', '20');
INSERT INTO `products`(`english_name`, `polish_name`, `glycemic_index`, `carbohydrate`) VALUES ('lentils', 'soczewica', '24.6', '30');
INSERT INTO `products`(`english_name`, `polish_name`, `glycemic_index`, `carbohydrate`) VALUES ('cashews', 'orzechy nerkowca', '25.2', '27');
INSERT INTO `products`(`english_name`, `polish_name`, `glycemic_index`, `carbohydrate`) VALUES ('peanuts', 'orzeszki ziemne', '14.25', '6');
INSERT INTO `products`(`english_name`, `polish_name`, `glycemic_index`, `carbohydrate`) VALUES ('popcorn', 'popcorn', '66.33', '63');
INSERT INTO `products`(`english_name`, `polish_name`, `glycemic_index`, `carbohydrate`) VALUES ('coca cola', 'coca cola', '63.0', '10');
INSERT INTO `products`(`english_name`, `polish_name`, `glycemic_index`, `carbohydrate`) VALUES ('bagel', 'bajgiel', '72.0', '51');
INSERT INTO `products`(`english_name`, `polish_name`, `glycemic_index`, `carbohydrate`) VALUES ('pita', 'pita', '97.0', '54');
INSERT INTO `products`(`english_name`, `polish_name`, `glycemic_index`, `carbohydrate`) VALUES ('hummus', 'hummus', '23.5', '8');
INSERT INTO `products`(`english_name`, `polish_name`, `glycemic_index`, `carbohydrate`) VALUES ('walnuts', 'orzechy włoskie', '20.0', '7');
INSERT INTO `products`(`english_name`, `polish_name`, `glycemic_index`, `carbohydrate`) VALUES ('coconut', 'kokos', '10.0', '6');
INSERT INTO `products`(`english_name`, `polish_name`, `glycemic_index`, `carbohydrate`) VALUES ('cauliflower', 'kalafior', '32.0', '3');
INSERT INTO `products`(`english_name`, `polish_name`, `glycemic_index`, `carbohydrate`) VALUES ('lettuce', 'sałata', '32.0', '2');
INSERT INTO `products`(`english_name`, `polish_name`, `glycemic_index`, `carbohydrate`) VALUES ('broccoli', 'brokół', '32.0', '4');
INSERT INTO `products`(`english_name`, `polish_name`, `glycemic_index`, `carbohydrate`) VALUES ('cabbage', 'kapusta', '44.0', '3');
INSERT INTO `products`(`english_name`, `polish_name`, `glycemic_index`, `carbohydrate`) VALUES ('onion', 'cebula', '27.0', '8');
INSERT INTO `products`(`english_name`, `polish_name`, `glycemic_index`, `carbohydrate`) VALUES ('spinach', 'szpinak', '32.0', '1');
INSERT INTO `products`(`english_name`, `polish_name`, `glycemic_index`, `carbohydrate`) VALUES ('eggplant', 'bakłażan', '30.0', '3');
INSERT INTO `products`(`english_name`, `polish_name`, `glycemic_index`, `carbohydrate`) VALUES ('tomato', 'pomodor', '38.0', '3');
INSERT INTO `products`(`english_name`, `polish_name`, `glycemic_index`, `carbohydrate`) VALUES ('carrot', 'marchewka', '46.83', '7');
INSERT INTO `products`(`english_name`, `polish_name`, `glycemic_index`, `carbohydrate`) VALUES ('pumpkin', 'dynia', '72.0', '6');
INSERT INTO `products`(`english_name`, `polish_name`, `glycemic_index`, `carbohydrate`) VALUES ('asparagus', 'szparag', '32.0', '2');
INSERT INTO `products`(`english_name`, `polish_name`, `glycemic_index`, `carbohydrate`) VALUES ('celery', 'seler', '32.0', '1');
INSERT INTO `products`(`english_name`, `polish_name`, `glycemic_index`, `carbohydrate`) VALUES ('cucumber', 'ogórek', '15.0', '1');
INSERT INTO `products`(`english_name`, `polish_name`, `glycemic_index`, `carbohydrate`) VALUES ('pepper', 'papryka', '10.0', '3');
INSERT INTO `products`(`english_name`, `polish_name`, `glycemic_index`, `carbohydrate`) VALUES ('macadamia nuts', 'orzechy makadamia', '10.0', '5');
INSERT INTO `products`(`english_name`, `polish_name`, `glycemic_index`, `carbohydrate`) VALUES ('egg', 'jajko', '0.0', '0');
INSERT INTO `products`(`english_name`, `polish_name`, `glycemic_index`, `carbohydrate`) VALUES ('peanut butter', 'masło orzechowe', '14.0', '14');
INSERT INTO `products`(`english_name`, `polish_name`, `glycemic_index`, `carbohydrate`) VALUES ('tahini', 'tahini', '0.0', '0');
INSERT INTO `products`(`english_name`, `polish_name`, `glycemic_index`, `carbohydrate`) VALUES ('cheese', 'ser żółty', '27.0', '1');
INSERT INTO `products`(`english_name`, `polish_name`, `glycemic_index`, `carbohydrate`) VALUES ('turkey breast', 'pierś z indyka', '0.0', '0');
INSERT INTO `products`(`english_name`, `polish_name`, `glycemic_index`, `carbohydrate`) VALUES ('chicken breast', 'pierś z kurczaka', '0.0', '0');
INSERT INTO `products`(`english_name`, `polish_name`, `glycemic_index`, `carbohydrate`) VALUES ('tofu', 'tofu', '15.0', '2');
INSERT INTO `products`(`english_name`, `polish_name`, `glycemic_index`, `carbohydrate`) VALUES ('blueberries', 'borówki amerykańskie', '40.0', '12');
INSERT INTO `products`(`english_name`, `polish_name`, `glycemic_index`, `carbohydrate`) VALUES ('zucchini', 'cukinia', '15.0', '2');
INSERT INTO `products`(`english_name`, `polish_name`, `glycemic_index`, `carbohydrate`) VALUES ('shrimp', 'krewetki', '50.0', '0');
INSERT INTO `products`(`english_name`, `polish_name`, `glycemic_index`, `carbohydrate`) VALUES ('lamb', 'jagnięcina', '0.0', '0');
INSERT INTO `products`(`english_name`, `polish_name`, `glycemic_index`, `carbohydrate`) VALUES ('pork', 'wieprzowina', '0.0', '0');
INSERT INTO `products`(`english_name`, `polish_name`, `glycemic_index`, `carbohydrate`) VALUES ('cranberries', 'żurawina', '45.0', '8');
INSERT INTO `products`(`english_name`, `polish_name`, `glycemic_index`, `carbohydrate`) VALUES ('bulgur', 'kasza bulgur', '47.0', '58');
INSERT INTO `products`(`english_name`, `polish_name`, `glycemic_index`, `carbohydrate`) VALUES ('sugar', 'cukier', '70.09', '100');
INSERT INTO `products`(`english_name`, `polish_name`, `glycemic_index`, `carbohydrate`) VALUES ('maple syrup', 'syrop klonowy', '36.5', '67');
INSERT INTO `products`(`english_name`, `polish_name`, `glycemic_index`, `carbohydrate`) VALUES ('chocolate', 'czekolada', '42.6', '55');
